<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SmsCampaign extends Model
{
    use HasFactory;
    use HasUuids;

    protected $fillable = [
        'name',
    ];

    protected static function boot()
    {
        static::creating(function ($model) {
            $model->team_id = auth()->user()->currentTeam->id;
        });

        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function team()
    {
        return $this->belongsTo(Team::class);
    }

    public function sends()
    {
        return $this->hasMany(SmsCampaignSend::class, 'campaign_id');
    }
}
