<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @property string $meta
 */
class SmsCampaign extends Model
{
    use HasFactory;
    use HasUuids;
    use SoftDeletes;

    protected $fillable = [
        'sms_campaign_plan_id',
        'name',
        'team_id',
        'meta',

    ];

    protected static function boot()
    {
        static::creating(function ($model) {
            if (empty($model->team_id) && auth()->user()) {
                $model->team_id = auth()->user()->currentTeam->id;
            }
        });

        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function team()
    {
        return $this->belongsTo(Team::class);
    }

    public function sends()
    {
        return $this->hasMany(SmsCampaignSend::class, 'sms_campaign_id');
    }

    public function setLists(array $list_ids)
    {
        $this->addMeta('lists', $list_ids);
    }

    private function addMeta($key, $value)
    {
        $meta = $this->getMeta();
        $meta[$key] = $value;
        $this->meta = json_encode($meta);
        $this->save();
    }

    private function getMeta(){
        $meta = json_decode($this->meta, true);

        return $meta ? $meta : [];
    }

    public function setSettings(array $array)
    {
        $this->addMeta('settings', $array);
    }

    public function offers()
    {
        return $this->belongsToMany(Offer::class, 'offer_campaign', 'sms_campaign_id', 'offer_id');
    }
}
