name: Deploy to demo
on:
  push:
    braches: ["actions"]
jobs:
  stop-current-build:
    runs-on: demo-v2
    steps:
      - uses: actions/checkout@v3
      - run: ./vendor/bin/sail down || true
  
  build:
    runs-on: demo-v2
    needs: stop-current-build
    container: 
      image: php:8.1-cli
      env: 
        DEPENDENSIES: libfreetype-dev libjpeg62-turbo-dev libpng-dev libzip-dev sudo
        EXTENSIONS: gd zip pcntl
        PECL_EXTENTIONS: redis
    steps:
    - run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - run: apt update && apt install -y ${DEPENDENSIES}
    - run: docker-php-ext-install ${EXTENSIONS}
    - run: yes '' | pecl install -o -f ${PECL_EXTENTIONS} &&  rm -rf /tmp/pear &&  docker-php-ext-enable ${PECL_EXTENTIONS}
    - run: composer install
    - run: chown -R 1000:1000 .
  
  deploy:
    runs-on: demo-v2
    needs: build
    steps:
    - run: |
        sed -i '/^ARG single_binary_location_url/s/^/#/g' ./docker/clickhouse/Dockerfile
        sed -i '/#ARG single_binary_location_url.*amd64/s/^#//g' ./docker/clickhouse/Dockerfile
        sed -i '/image: yandex.clickhouse-server/s/^/#/g' docker-compose.yml
    - run: cp .env.example .env
    - run: ./vendor/bin/sail up -d
    - run: ./vendor/bin/sail artisan migrate:fresh --seed

