name: Run tests
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - run: id && pwd && cat /etc/os-release
    - uses: actions/checkout@v3
    - uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - run: docker run --rm -v ${PWD}/:/app -w /app -u 1000 smsedge/msgr-v2:composer-local composer install
  
  build_node:
    runs-on: ubuntu-latest
    needs: build
    container: 
      image: node
      volumes: 
      - .:/app
    steps:
    - run: cd /app/nuxt && npm install
    - run: chown -R 1000:1000 .
  
  deploy:
    runs-on: ubuntu-latest
    needs: build_node
    steps:
    - run: |
        sed -i '/^ARG single_binary_location_url/s/^/#/g' ./docker/clickhouse/Dockerfile
        sed -i '/#ARG single_binary_location_url.*amd64/s/^#//g' ./docker/clickhouse/Dockerfile
        sed -i '/image: yandex.clickhouse-server/s/^/#/g' docker-compose.yml
    - run: cp .env.example .env
    - run: ./vendor/bin/sail up -d
    - run: sleep 30 && ./vendor/bin/sail artisan migrate:fresh --seed
    - run: ./vendor/bin/sail test || true
